name: Build and Release Manga to PDF

on:
  workflow_dispatch:

permissions:
  contents: write  # Allows the workflow to create tags and publish releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Adjust if necessary

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile --name manga_to_pdf mangatopdf.py

      - name: Prepare Release Asset
        run: |
          mkdir release-asset
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv dist/manga_to_pdf.exe release-asset/manga_to_pdf-windows.exe
          else
            mv dist/manga_to_pdf release-asset/manga_to_pdf-linux
            chmod +x release-asset/manga_to_pdf-linux
          fi
        shell: bash

      - name: Create Release Description
        run: |
          echo "Manga to PDF Converter - v${{ github.run_number }}" > release_description.md
          echo "" >> release_description.md
          echo "This release includes executables for Windows and Linux." >> release_description.md
          echo "" >> release_description.md
          echo "## Windows" >> release_description.md
          echo "Download the 'manga_to_pdf-windows.exe' file and run it directly." >> release_description.md
          echo "" >> release_description.md
          echo "## Linux" >> release_description.md
          echo "1. Download the 'manga_to_pdf-linux' file." >> release_description.md
          echo "2. Open a terminal in the directory containing the downloaded file." >> release_description.md
          echo "3. Run the program with: \`./manga_to_pdf-linux\`" >> release_description.md
          echo "" >> release_description.md
          echo "For more details, please refer to the project documentation." >> release_description.md
        shell: bash

      - name: Create Git Tag
        run: |
          TAG_NAME="v${{ github.run_number }}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          body_path: release_description.md
          files: release-asset/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
