name: Build and Release Manga to PDF

on:
  workflow_dispatch:

permissions:
  contents: write  # Allows the workflow to create tags and publish releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust if necessary

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Build with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile --name manga_to_pdf mangatopdf.py  # Build the executable
          
      - name: Archive the executable
        run: |
          mkdir output
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            move dist\manga_to_pdf.exe output\
          else
            mv dist/manga_to_pdf output/
          fi

      - name: Create Git Tag
        id: create_tag
        run: |
          TAG_NAME="v${{ github.run_number }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}  # Change to tag_name
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
